#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -x
if [ -d $OPENSHIFT_DATA_DIR/activemq ]
then
    exit 0
else
	mkdir $OPENSHIFT_DATA_DIR/activemq-data
    cp -rf $OPENSHIFT_REPO_DIR/diy/activemq $OPENSHIFT_DATA_DIR
    cd $OPENSHIFT_DATA_DIR/activemq
    rm -rf logs
    ln -s $OPENSHIFT_DIY_LOG_DIR logs
fi

